algoritmo "3003_10"
// Função :
// Autor :
// Data : 01/04/2016
// Seção de Declarações 
var
   a : inteiro
inicio
// Seção de Comandos
   escreval("Forneça um número inteiro.")
   leia(a)
   escreval()
   se (a>=0) entao
      se (a>0) entao
         escreval("O número é positivo.")
      senao
         escreval("O número é neutro (0).")
      fimse
   senao
      escreval("O número é negativo.")
   fimse
fimalgoritmo
