algoritmo "3003_12"
// Função :
// Autor :
// Data : 01/04/2016
// Seção de Declarações 
var
   a:inteiro
inicio
// Seção de Comandos 
   escreval("Forneça um número inteiro.")
   escreval("De preferência que esteja entre 1 e 9.")
   leia(a)
   escreval()
   se (a>=1) e (a<=9) entao
      escreval("O valor está na faixa permitida")
   senao
      escreval("O valor está fora da faixa permitida")
   fimse
fimalgoritmo
